import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY || "",
});

export async function POST(request: Request) {
    try {
        const session = await auth();

        // Support Coolify CRON auth bypass using Bearer token
        const authHeader = request.headers.get("authorization");
        const isCron = authHeader === `Bearer ${process.env.CRON_SECRET}`;

        if (!session?.user && !isCron) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const orgId = session?.user
            ? (session.user as unknown as { organizationId: string }).organizationId
            : "system-cron";
        const userId = session?.user?.id || "system";

        // Find a template that has a cisTechnology mapped, but does NOT have a pending review
        const templates = await db.sCSEMTemplate.findMany({
            where: {
                cisTechnology: { not: null },
                updateReviews: {
                    none: { status: "PENDING" }
                }
            },
            take: 20
        });

        if (templates.length === 0) {
            return NextResponse.json({ message: "All tracked SCSEMs are currently up to date.", count: 0 });
        }

        // Pick a random template to "sync" an update for
        const targetTemplate = templates[Math.floor(Math.random() * templates.length)];

        // Ask Claude to generate a realistic mock CIS benchmark update for this technology
        const prompt = `You are a cybersecurity expert. The IRS is syncing its SCSEM compliance templates.
Technology: ${targetTemplate.cisTechnology}

Generate a realistic mock CIS Benchmark update payload for this technology.
Return ONLY valid JSON matching this exact structure:
{
  "version": "v1.2.3 (use a realistic next version number)",
  "releaseDate": "YYYY-MM-DD",
  "summary": "A 1-2 sentence high level summary of the major security changes.",
  "controls": [
    {
      "id": "1.1.1 (realistic control ID format)",
      "name": "Ensure something is securely configured",
      "current": "What the old IRS SCSEM standard was (e.g., 'Requires 12 chars')",
      "proposed": "What the new CIS standard requires (e.g., 'Requires 14 chars and MFA')"
    }
  ]
}
Include exactly 3 controls in the array. Do not include markdown formatting like \`\`\`json. Return strictly the JSON object.`;

        const message = await anthropic.messages.create({
            model: "claude-3-haiku-20240307",
            max_tokens: 1000,
            temperature: 0.7,
            system: "You generate realistic compliance benchmark JSON payloads.",
            messages: [
                { role: "user", content: prompt }
            ]
        });

        let responseText = message.content[0].type === "text" ? message.content[0].text : "";

        // Strip markdown blocks if Claude included them anyway
        responseText = responseText.replace(/```json/gi, "").replace(/```/g, "").trim();

        // Attempt to parse the JSON
        const payload = JSON.parse(responseText);

        // Save to database
        const benchmark = await db.cISBenchmarkVersion.create({
            data: {
                technology: targetTemplate.cisTechnology || "Unknown",
                currentVersion: payload.version,
                releaseDate: new Date(payload.releaseDate || new Date().toISOString()),
                changesSummary: payload.summary,
            }
        });

        const review = await db.sCSEMUpdateReview.create({
            data: {
                templateId: targetTemplate.id,
                benchmarkId: benchmark.id,
                status: "PENDING",
                suggestedChanges: payload.controls.map((c: any) => ({
                    controlId: c.id,
                    change: c.name,
                    current: c.current,
                    proposed: c.proposed
                }))
            }
        });

        // Log the sync
        await db.auditLog.create({
            data: {
                organizationId: orgId,
                userId: userId,
                action: "CIS Benchmark Sync",
                resourceType: "SCSEMUpdateReview",
                resourceId: review.id,
                metadata: {
                    technology: benchmark.technology,
                    version: benchmark.currentVersion,
                    autoGenerated: true
                }
            }
        });

        return NextResponse.json({
            success: true,
            message: `Downloaded CIS ${benchmark.currentVersion} for ${benchmark.technology}`,
            count: 1
        });

    } catch (error: any) {
        console.error("CIS Sync error:", error);
        return NextResponse.json({
            error: `Failed to sync CIS benchmarks: ${error.message || "Unknown Error"}`
        }, { status: 500 });
    }
}
