"use client";

import { useState, useRef, useEffect } from "react";
import { Bell, AlertTriangle, ShieldAlert, FileSpreadsheet, Info } from "lucide-react";

const mockNotifications = [
    {
        id: "cis-mock-disclaimer",
        title: "CIS Benchmark API Limit",
        description: "The official CIS SecureSuite API requires a paid enterprise membership. Generated payloads in this demo are realistic mock updates generated by Claude 3 Haiku for demonstration purposes.",
        time: "System Notice",
        icon: Info,
        color: "text-blue-400",
        bgColor: "bg-blue-500/10",
        borderColor: "border-blue-500/20"
    },
    {
        id: "update-1",
        title: "Windows Server 2022 Updates",
        description: "v3.0.0 is available. 3 suggested control modifications pending your review.",
        time: "2 hours ago",
        icon: ShieldAlert,
        color: "text-amber-400",
        bgColor: "bg-amber-500/10",
        borderColor: "border-amber-500/20"
    },
    {
        id: "update-2",
        title: "Red Hat Enterprise Linux Updates",
        description: "v4.0.0 is available. New SELinux enforcements require your review.",
        time: "5 hours ago",
        icon: ShieldAlert,
        color: "text-amber-400",
        bgColor: "bg-amber-500/10",
        borderColor: "border-amber-500/20"
    },
    {
        id: "incident-1",
        title: "High Severity Incident",
        description: "Unauthorized FTI access attempt detected on database server.",
        time: "1 day ago",
        icon: AlertTriangle,
        color: "text-red-400",
        bgColor: "bg-red-500/10",
        borderColor: "border-red-500/20"
    }
];

export function NotificationsMenu() {
    const [isOpen, setIsOpen] = useState(false);
    const menuRef = useRef<HTMLDivElement>(null);

    // Close when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };
        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, []);

    return (
        <div className="relative" ref={menuRef}>
            {/* Notification Button */}
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="relative p-2 rounded-full transition-colors hover:bg-slate-800/50 text-slate-400 hover:text-white"
                aria-label="View notifications"
            >
                <Bell className="w-5 h-5" />
                <span className="absolute top-1.5 right-1.5 w-2 h-2 rounded-full bg-red-500 ring-2 ring-[var(--sky-navy)]" />
            </button>

            {/* Dropdown Menu */}
            {isOpen && (
                <div className="absolute top-full lg:left-0 right-0 mt-2 w-80 sm:w-96 glass rounded-xl border border-slate-700 shadow-2xl z-[100] overflow-hidden transform origin-top-right transition-all animate-in fade-in slide-in-from-top-2">
                    {/* Header */}
                    <div className="px-4 py-3 border-b border-slate-700/50 bg-slate-800/30 flex justify-between items-center">
                        <h3 className="font-semibold text-white">Notifications</h3>
                        <span className="text-xs px-2 py-0.5 rounded-full bg-sky-500/20 text-sky-400 font-medium">
                            {mockNotifications.length} New
                        </span>
                    </div>

                    {/* List */}
                    <div className="max-h-[70vh] overflow-y-auto">
                        {mockNotifications.map((notif) => (
                            <div
                                key={notif.id}
                                className="p-4 border-b last:border-0 border-slate-700/30 hover:bg-slate-800/30 transition-colors flex gap-4 cursor-pointer"
                            >
                                <div className={`mt-1 flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center border ${notif.bgColor} ${notif.borderColor} ${notif.color}`}>
                                    <notif.icon className="w-4 h-4" />
                                </div>
                                <div className="flex-1 min-w-0">
                                    <p className="text-sm font-medium text-white mb-1">
                                        {notif.title}
                                    </p>
                                    <p className="text-xs text-slate-400 mb-2 leading-relaxed">
                                        {notif.description}
                                    </p>
                                    <p className="text-[10px] font-medium text-slate-500 uppercase tracking-wider">
                                        {notif.time}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Footer */}
                    <div className="p-3 border-t border-slate-700/50 bg-slate-800/30 text-center">
                        <button
                            onClick={() => setIsOpen(false)}
                            className="text-xs text-sky-400 hover:text-sky-300 font-medium transition-colors"
                        >
                            Mark all as read
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
